[INSERT]
default = """
INSERT INTO "collector"."server" (
    name, host, port, username, password, ssl_mode,
    ignore_pattern, ignore_tables, include_tables
) VALUES (
    %(name)s, %(host)s, %(port)s, %(username)s, %(password)s, %(ssl_mode)s,
    %(ignore_pattern)s, %(ignore_tables)s, %(include_tables)s
) ON CONFLICT DO NOTHING
"""

[SELECT]
by_name = """
SELECT 
    id, ignore_pattern, ignore_tables, include_tables 
FROM "collector"."server"
WHERE  name       = %(name)s
  AND  deleted_at IS NULL
"""

by_server_id = """
SELECT id FROM "collector"."server"
WHERE id = %(server_id)s
AND deleted_at IS NULL
"""
